project:
  type: website

website:
  navbar:
    pinned: true
    title: false
    logo: logo3.png
    logo-alt: "Our logo"
    left:
      - text: "Für Studenten/-innen"
        file: studenten.qmd
      - text: "Für Dozenten/-innen"
        file: dozenten.qmd
      - text: "Für Programmierer/-innen"
        file: programmierer.qmd
      - text: "Team"
        file: team.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/shevandrin/qti
      # - icon: twitter
      #   href: https://twitter.com
format:
  html:
    theme:
      light: [flatly]
    css: styles.css
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px

